# Digital Ocean App Platform Configuration
# Multi-service deployment for annotat.ee

name: annotation-platform
region: ams3

domains:
  - domain: annotat.ee
    type: PRIMARY
    minimum_tls_version: "1.2"

services:
  # Main Node.js API Service
  - name: api
    source_dir: /
    dockerfile_path: Dockerfile.production
    github:
      repo: abergman/annotation-platform
      branch: main
      deploy_on_push: true
    
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 8080
    
    routes:
      - path: /api
      - path: /health
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: HOST
        value: "0.0.0.0"
      - key: DOMAIN
        value: annotat.ee
      - key: MONGODB_URI
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET  
        scope: RUN_TIME
        type: SECRET
      - key: SESSION_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGIN
        value: https://annotat.ee
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  # React Frontend Static Site
  - name: frontend
    source_dir: /frontend
    dockerfile_path: frontend/Dockerfile.frontend
    github:
      repo: abergman/annotation-platform
      branch: main
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /
        preserve_path_prefix: false
    
    envs:
      - key: VITE_API_URL
        value: https://annotat.ee/api
      - key: VITE_APP_NAME
        value: "Academic Annotation Platform"
      - key: VITE_APP_VERSION
        value: "1.0.0"