# Digital Ocean App Platform Configuration
# Working API-only configuration for annotat.ee

name: annotation-platform
region: ams3

domains:
  - domain: annotat.ee
    type: PRIMARY

services:
  # Main Node.js API Service (MongoDB backend)
  - name: api
    source_dir: /
    dockerfile_path: Dockerfile.production
    github:
      repo: abergman/annotation-platform
      branch: main
      deploy_on_push: true
    
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 8080
    
    routes:
      - path: /
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: HOST
        value: "0.0.0.0"
      - key: DOMAIN
        value: annotat.ee
      - key: MONGODB_URI
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET  
        scope: RUN_TIME
        type: SECRET
      - key: SESSION_SECRET
        scope: RUN_TIME
        type: SECRET
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

# Frontend temporarily removed due to build issues
# Will add back after fixing TypeScript/build problems