name: academic-annotation-platform
region: ams3

services:
# Python FastAPI Backend - Main API Service
- name: api-backend
  source_dir: /
  github:
    repo: abergman/annotatee
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile.production
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 8000
  
  routes:
  - path: /api
  - path: /health
  - path: /
  
  health_check:
    http_path: /health
    initial_delay_seconds: 60
    period_seconds: 30
    timeout_seconds: 10
    failure_threshold: 3
    success_threshold: 2
  
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8000"
  - key: HOST
    value: "0.0.0.0"
  - key: DEBUG
    value: "False"
    
  # Database Configuration (using existing managed database)
  - key: DATABASE_URL
    value: ${DATABASE_URL}
  - key: DB_HOST
    value: ${DB_HOST}
  - key: DB_PORT
    value: ${DB_PORT}
  - key: DB_NAME
    value: ${DB_NAME}
  - key: DB_USER
    value: ${DB_USER}
  - key: DB_PASSWORD
    value: ${DB_PASSWORD}
    
  # Security & Authentication
  - key: SECRET_KEY
    value: ${SECRET_KEY}
  - key: JWT_SECRET
    value: ${JWT_SECRET}
  - key: ACCESS_TOKEN_EXPIRE_MINUTES
    value: "30"
  - key: BCRYPT_ROUNDS
    value: "12"
    
  # CORS Configuration
  - key: ALLOWED_ORIGINS
    value: "${APP_URL},https://${APP_DOMAIN}"
    
  # File Upload Settings
  - key: MAX_FILE_SIZE
    value: "10485760"
  - key: UPLOAD_DIR
    value: "/app/uploads"
  - key: EXPORT_DIR
    value: "/app/exports"
    
  # Monitoring & Logging
  - key: LOG_LEVEL
    value: "info"
  - key: LOG_DIR
    value: "/app/logs"
    
  # Performance Settings
  - key: RATE_LIMIT_WINDOW
    value: "15"
  - key: RATE_LIMIT_MAX
    value: "100"

# Node.js WebSocket Server - Real-time Features
- name: websocket-server
  source_dir: /
  github:
    repo: abergman/annotatee
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile.websocket
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 8001
  
  routes:
  - path: /ws
  
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 30
    timeout_seconds: 5
    failure_threshold: 3
    success_threshold: 2
  
  envs:
  - key: NODE_ENV
    value: production
  - key: WEBSOCKET_PORT
    value: "8001"
  - key: MAX_ROOMS_PER_USER
    value: "10"
  - key: MESSAGE_QUEUE_SIZE
    value: "1000"
  - key: PRESENCE_TIMEOUT
    value: "300"
    
  # API Integration
  - key: API_URL
    value: "${api-backend.PUBLIC_URL}"
  - key: FRONTEND_URL
    value: "${frontend.PUBLIC_URL}"
    
  # Redis Configuration (optional for scaling)
  - key: REDIS_URL
    value: ${REDIS_URL}

# React Frontend - Static Site
- name: frontend
  source_dir: /frontend
  github:
    repo: abergman/annotatee
    branch: main
    deploy_on_push: true
  build_command: npm run build:production
  instance_count: 1
  instance_size_slug: basic-xxs
  
  routes:
  - path: /
    preserve_path_prefix: false
  
  envs:
  - key: VITE_API_URL
    value: "${api-backend.PUBLIC_URL}/api"
  - key: VITE_WS_URL
    value: "wss://${websocket-server.PUBLIC_URL}/ws"
  - key: VITE_APP_NAME
    value: "Academic Annotation Platform"
  - key: VITE_APP_VERSION
    value: "1.0.0"

# PostgreSQL Database (Managed)
databases:
- name: annotation-db
  engine: PG
  version: "15"
  size: db-s-1vcpu-1gb
  num_nodes: 1
  production: true
  
# Redis Cache (Optional - for WebSocket scaling)
databases:
- name: annotation-redis
  engine: REDIS
  version: "7"
  size: db-s-1vcpu-1gb
  num_nodes: 1
  production: true

# Environment Variables (Configure in DigitalOcean Dashboard)
# Required variables to set manually:
# - SECRET_KEY: Long random string for app security
# - JWT_SECRET: Long random string for JWT tokens  
# - DATABASE_URL: Auto-populated by managed database
# - REDIS_URL: Auto-populated by managed Redis (if used)
# - DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASSWORD: Auto-populated
